apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: monitoring  # Make sure Prometheus is watching this namespace
  labels:
    release: stable  # Match your Prometheus instance
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: 8083
      interval: 30s
      path: /metrics
