apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-external
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
  - port: http
    path: /prometheus
  selector:
    matchLabels:
      app: jenkins-external
  namespaceSelector:
    any: true
