apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-metrics
  namespace: monitoring
  labels:
    app: jenkins-metrics  # Label for the ServiceMonitor
    release: prometheus   # Must match your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app: jenkins-external  # Must match the Service labels
  endpoints:
  - port: http  # Must match the port name in the Service
    path: /prometheus/  # Path where Jenkins exposes Prometheus metrics
    interval: 5s  # Optional: Scrape interval
  namespaceSelector:
    any: true  # Scrape across all namespaces
