apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-monitor
  namespace: monitoring  # Ensure this is the namespace where Prometheus is running
  labels:
    release: prometheus
spec:
  endpoints:
    - port: web  # The name of the port in the Service definition
      path: /prometheus/
      interval: 15s
      scheme: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: jenkins
