apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: monitoring
  labels:
    app: jenkins
spec:
  type: ExternalName
  externalName: 54.242.131.12  # Jenkins EC2 Public IP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
