apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkinsci-server
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
  - port: http
    path: /prometheus/
  selector:
    matchLabels:
      app: jenkinsci-server
  namespaceSelector:
    any: true
