apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app: argocd-server
    release: prometheus  # Must match your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server  # Label from Argo CD service
  endpoints:
  - port: metrics  # Name of the port in the Argo CD service
    path: /metrics
