apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-rollouts-metrics
  namespace: argo-rollouts
  labels:
    app: argo-rollouts-metrics
    release: prometheus  # Must match your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts-metrics  # Label from Argo CD service
  endpoints:
  - port: metrics  # Name of the port in the Argo CD service
    path: /metrics
