apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sg-decoding-frontend-monitor
  namespace: sgdecoding
  labels:
    release: prometheus  # Match the Prometheus release name
    helm.sh/chart: sg-decoding-1.0.0
    app.kubernetes.io/name: sg-decoding
    app.kubernetes.io/instance: sgdecoding
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sg-decoding
      app.kubernetes.io/instance: sgdecoding
  namespaceSelector:
    matchNames:
      - sgdecoding
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
