apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sg-decoding-monitor
  namespace: sgdecoding
  labels:
    release: prometheus  # Match the Prometheus instance
spec:
  selector:
    matchLabels:
      app: sg-decoding-web  # Match the service labels
  endpoints:
    - port: metrics  # Port name in the service
      path: /metrics  # Path to metrics endpoint
