apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rollout-bluegreen-active-monitor
  namespace: sgdecoding  # Ensure this matches the namespace of your service
  labels:
    app.kubernetes.io/name: sg-decoding
    app.kubernetes.io/instance: sgdecoding
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sg-decoding
      app.kubernetes.io/instance: sgdecoding
  namespaceSelector:
    matchNames:
      - sgdecoding  # Ensure this matches the namespace of your service
  endpoints:
    - port: http  # Matches the port name in your service
      interval: 30s  # Scrape interval
      path: /metrics  # Default metrics endpoint, adjust if your app uses a different path
