{
 "title": "Argo Rollouts",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rollout_namespace",
    "label": "rollout namespace",
    "query": {
     "query": "label_values(rollout_info,namespace)"
    }
   },
   {
    "name": "rollout_name",
    "label": "rollout name",
    "query": {
     "query": "label_values(rollout_info{namespace=\"$rollout_namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime (controller)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Total Rollouts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"sgdecoding\"}[5m])) \n/ \nsum(kube_pod_container_resource_requests{namespace=\"sgdecoding\", resource=\"cpu\"}) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"sgdecoding\"}) \n/ \nsum(kube_pod_container_resource_requests{namespace=\"sgdecoding\", resource=\"memory\"}) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollouts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\"}) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  { "title": "Canary Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Canary Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rollout_phase{name=\"$rollout_name\", namespace=\"$rollout_namespace\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Canary Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count by (created_by_name) (kube_pod_info{namespace=\"sgdecoding\", created_by_name=~\"sg-decoding-api-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Blue Green Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "BlueGreen Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count by (created_by_name) (kube_pod_info{namespace=\"sgdecoding\", created_by_name=~\"sg-decoding-web-.*\"})",
     "legendFormat": "{{created_by_name}}"
    },
    {
     "expr": "sum (kube_pod_info{namespace=\"sgdecoding\", created_by_name=~\"sg-decoding-web-.*\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Stable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{phase=\"Completed\",job=\"argo-rollouts-metrics\"} == 1)"
    }
   ]
  },
  {
   "title": "Progressing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{phase=\"Progressing\",job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{phase=\"Paused\",job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\",phase=\"Error\"} == 1)"
    }
   ]
  },
  {
   "title": "Aborted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\",phase=\"Abort\"} == 1)"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\",phase=\"Timeout\"} == 1)"
    }
   ]
  },
  {
   "title": "Reconcile Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rollout_reconcile_count{job=\"argo-rollouts-metrics\"}[10m]))"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(rollout_reconcile_bucket[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argo-rollouts-metrics\"}"
    }
   ]
  },
  { "title": "Rollout Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Phase",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rollout_info{job=\"argo-rollouts-metrics\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
    }
   ]
  },
  {
   "title": "Replicas (desired)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollout_info_replicas_desired{job=\"argo-rollouts-metrics\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
    }
   ]
  },
  {
   "title": "Replica (available)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollout_info_replicas_available{job=\"argo-rollouts-metrics\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
    }
   ]
  },
  {
   "title": "Replica (unavailable)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollout_info_replicas_unavailable{job=\"argo-rollouts-metrics\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
    }
   ]
  }
 ]
}